FROM netutils

RUN apt-get update && \
    apt-get install -y nginx

RUN echo "Hello Docker nginx container!" >  /var/www/html/index.nginx-debian.html

ENTRYPOINT /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
